name: CI

on: push

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-latest
    
    env:
      COVERITY: coverity_tool

    steps:
      - uses: actions/checkout@v2

      - name: Setup Maven Central
        uses: actions/setup-java@v2
        with:
          java-version: 8.0.292+10
          distribution: 'adopt'

      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Compile Test and Verify
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn --batch-mode clean verify -s settings.xml
        
